services:
  - type: web
    name: backend
    env: []
    startCommand: []
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: admin
    healthCheckPath: /
    healthCheckPort: 8000
    httpPort: 8000
    dockerfilePath: Dockerfile
    buildCommand: ""
    buildPath: ""
    useDockerBuildKit: false
    includeDockerConfig: false
    diskSizeMB: 256

  - type: web
    name: configurator
    env: []
    startCommand: []
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: "3306"
      - key: REDIS_CACHE
        value: redis-cache:6379
      - key: REDIS_QUEUE
        value: redis-queue:6379
      - key: SOCKETIO_PORT
        value: "9000"
    healthCheckPath: /
    healthCheckPort: 8000
    httpPort: 8000
    dockerfilePath: Dockerfile
    buildCommand: ""
    buildPath: ""
    useDockerBuildKit: false
    includeDockerConfig: false
    diskSizeMB: 256

# Add definitions for other services similarly...
